version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: FischerFactoryPROD
      DOCKER_INFLUXDB_INIT_PASSWORD: ----
      DOCKER_INFLUXDB_INIT_ORG: Remanufacturing Lab
      DOCKER_INFLUXDB_INIT_BUCKET: FischerFactory
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2

  telegraf:
    image: telegraf:latest
    volumes:
    # this should be changed to "telegraf.dev.conf" when devving
      - ./telegraf.prod.conf:/etc/telegraf/telegraf.conf